name: build artifacts

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: animepahe-downloader
          path: |
            ./build/animepahe-downloader-darwin-arm64
            ./build/animepahe-downloader-darwin-amd64
            ./build/animepahe-downloader-windows-amd64.exe
            ./build/animepahe-downloader-windows-arm64.exe
            ./build/animepahe-downloader-linux-amd64
            ./build/animepahe-downloader-linux-arm64
      
        

